# Generated by Django 5.2.4 on 2025-11-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attachment_storage_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('quote', 'Devis'), ('invoice', 'Facture'), ('justification', 'Justificatif'), ('pdf', 'PDF'), ('jpeg', 'Image JPEG'), ('png', 'Image PNG'), ('other', 'Autre')], default='other', max_length=20),
        ),
    ]
