# Generated by Django 5.2.4 on 2025-11-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attachment_storage_delivery_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='storage_delivery_type',
        ),
    ]
