# Generated by Django 5.2.4 on 2025-11-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_create_initial_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Personnel'), ('mg', 'Moyens Généraux'), ('accounting', 'Comptabilité'), ('director', 'Direction')], default='employee', max_length=20),
        ),
    ]
