# Generated by Django 5.2.4 on 2025-11-12 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_incidentreport_incidentcomment_provisionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='budget_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='budget_locked_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='BudgetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('committed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('on_hold', 'Suspendu'), ('closed', 'Clôturé')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'accounting'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet budgétaire',
                'verbose_name_plural': 'Projets budgétaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='budget_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='core.budgetproject'),
        ),
    ]
